spring.application.name: config-server

spring:
  cloud:
    config:
      server:
        git:
          uri: ${uri}
          username: ${username}
          password: ${github_token}
          default-label: ${repo_branch}

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
